### PR TITLE
Fix secondaryDisplay in jammy

### LINKED ISSUE #53: Workspace previews not working correctly on GNOME 42
Secondary monitor previews are often in the wrong spot and too small, primary monitor previews are often too small.

### PR DESCRIPTION
**Pull request by 13r0ck**

### CODE REVIEW

**Review by jackpot51 — APPROVED** [review]

**Review by jackpot51 — CHANGES_REQUESTED** [review]
This is not quite working for me. I have three identical 1440p monitors and the scale of the workspace previews on each is a little different

Screenshot from 2022-03-28 08-21-40

**Comment by 13r0ck** [comment]
@jackpot51 how about now?

**Review by jackpot51 — APPROVED** [review]
Fixed, good job!

**Review by jacobgkau — APPROVED** [review]
Fixes workspace picker display with 2+ monitors. With 1x1080p, 1x1440p, and 1x2160p@100%, the picker is appropriately sized and positioned on all displays:

Screenshot from 2022-03-28 14-21-39

With 1x2160p@200% (HiDPI) and 1x1440p@100%, the workspace picker is a little offset on the second display-- it's farther away from the edge than it should be (this also affects the 2160p@100% display if I plug it in); additionally, the windows overlap the picker on a HiDPI system even with no external displays plugged in:

Screenshot from 2022-03-28 14-12-57

The window overlap issue on HiDPI is not a regression and the workspace picker being offset on HiDPI is still an improvement over being entirely broken.

I also noticed on the regular (LoDPI) system that every time I _exit_ the Workspaces menu, the following shows up in journalctl:

```
Mar 28 14:24:34 pop-os gnome-shell[4654]: Object St.Bin (0x55786c6eced0), has been already disposed — impossible to access it. This might be caused by the object having been destroyed from C code using something such as destroy(), dispose(), or remove() vfuncs.
Mar 28 14:24:34 pop-os gnome-shell[4654]: == Stack trace for context 0x557866ae7190 ==
Mar 28 14:24:34 pop-os gnome-shell[4654]: #0   7fff3577abb0 b   /usr/share/gnome-shell/extensions/cosmic-workspaces@system76.com/workspaceThumbnail.js:186 (9a3b67d8830 @ 17)
```

But that is also not a regression.

**Pull request merged**
