### PR TITLE
Vertical workspaces styling

### LINKED ISSUE #1: Match 21.10 Workspace Picker to the COSMIC design
Styling has been slightly updated from 21.04
image

See more mockups here: https://www.figma.com/file/6vzaICveLGHnUqZrZ8XVrn/Workspaces-search?node-id=296%3A22007

### PR DESCRIPTION
**Pull request by isantop**
Updates the vertical workspaces styling to better match the mockups provided. Additionally, updates some of the code logic and settings preferences to better allow these changes to show.

Fixes #1

### CODE REVIEW

**Review by jackpot51 — APPROVED** [review]

**Comment by leviport** [comment]
When I installed this, I saw a message I don't normally see. I'm not sure if it's something I should be concerned about.

```
No such key “custom-theme” in schema “org.gnome.shell.extensions.dash-to-dock:ubuntu” as specified in override file “/usr/share/glib-2.0/schemas/10_ubuntu-dock.gschema.override”; ignoring override for this key.
```


<details>
<summary>Full output of `sudo apt update && sudo apt upgrade` after adding this branch, in case it's needed:</summary>

```
system76@pop-os:~$ sudo apt update && sudo apt upgrade 
Hit:1 http://apt.pop-os.org/proprietary impish InRelease
Hit:2 http://apt.pop-os.org/release impish InRelease
Hit:3 http://apt.pop-os.org/staging/new-styling impish InRelease
Hit:4 http://us.archive.ubuntu.com/ubuntu impish InRelease
Hit:5 http://us.archive.ubuntu.com/ubuntu impish-security InRelease
Hit:6 http://us.archive.ubuntu.com/ubuntu impish-updates InRelease
Hit:7 http://us.archive.ubuntu.com/ubuntu impish-backports InRelease
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
1 package can be upgraded. Run 'apt list --upgradable' to see it.
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Calculating upgrade... Done
The following packages will be upgraded:
  gnome-shell-extension-vertical-overview
1 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Need to get 25.1 kB of archives.
After this operation, 1,024 B of additional disk space will be used.
Do you want to continue? [Y/n] 
Get:1 http://apt.pop-os.org/staging/new-styling impish/main amd64 gnome-shell-extension-vertical-overview all 0.1.0~1633461169~21.10~d7c2eea [25.1 kB]
Fetched 25.1 kB in 0s (342 kB/s)                             
(Reading database ... 209885 files and directories currently installed.)
Preparing to unpack .../gnome-shell-extension-vertical-overview_0.1.0~1633461169~21.10~d7c2eea_all.deb ...
Unpacking gnome-shell-extension-vertical-overview (0.1.0~1633461169~21.10~d7c2eea) over (0.1.0~1633383091~21.10~0397ab6) ...
Setting up gnome-shell-extension-vertical-overview (0.1.0~1633461169~21.10~d7c2eea) ...
Processing triggers for libglib2.0-0:amd64 (2.68.4-1build1) ...
No such key “custom-theme” in schema “org.gnome.shell.extensions.dash-to-dock:ubuntu” as specified in override file “/usr/share/glib-2.0/schemas/10_ubuntu-dock.gschema.override”; ignoring override for this key.
```

</details>

**Comment by ids1024** [comment]
Looks like that warning from apt is due to the `cosmic-dock` package, which owns that file, not `gnome-shell-extension-vertical-overview`. It should be harmless, though we probably want to fix it if it's going to print that when updating any package with gsettings schemas.

Edit: Pushed a commit to `cosmic-dock` just removing that file, since we don't need it.

**Comment by isantop** [comment]
What are you getting as the output of `apt policy gnome-shell-extension-cosmic-dock`?

**Comment by ids1024** [comment]
Hm, I see https://github.com/pop-os/cosmic-dock/commit/535aba1d0651263946e1918bb5e24c9cf99138ab added the `custom-theme=true` line. This doesn't do anything since there isn't such a key in `org.gnome.shell.extensions.dash-to-dock.gschema.xml`. I guess that should be `apply-custom-theme`?

And I don't think we want a `10_ubuntu-dock.gschema.override` file (is that actually used in the pop session? I'm not sure what if any effect the `:ubuntu` suffix in the file actually has). The previous Pop changes are just made in the `.gschema.xml` file. Otherwise I guess we'd want the file to be named something like `10_cosmic-dock.gschema.override`.

**Comment by ids1024** [comment]
The exact way `.gschema.override` files work doesn't seem to be documented well, but the `:ubuntu` string is the in the `desktop_id` in the [source code](https://gitlab.gnome.org/GNOME/glib/-/blob/main/gio/glib-compile-schemas.c) for `glib-compile-schemas`, which I believe refers to the gnome-session name, so changes to that file have no impact on Pop!_OS.

So I guess my removal of that file is correct, and this should indeed be changed elsewhere.

**Comment by leviport** [comment]
> What are you getting as the output of `apt policy gnome-shell-extension-cosmic-dock`?

Sorry, forgot to answer this earlier. Here's that output:
```
gnome-shell-extension-cosmic-dock:
  Installed: 70~ubuntu1pop0~1633440690~21.10~c827be5
  Candidate: 70~ubuntu1pop0~1633440690~21.10~c827be5
  Version table:
 *** 70~ubuntu1pop0~1633440690~21.10~c827be5 1001
       1001 http://apt.pop-os.org/release impish/main amd64 Packages
       1001 http://apt.pop-os.org/release impish/main i386 Packages
        100 /var/lib/dpkg/status
 ```

**Comment by isantop** [comment]
@leviport I don't think that specific issue is related to this PR, but rather as @ids1024 mentioned above that extra file in the Cosmic Dock changes. Removing that file should probably correct that.

**Comment by leviport** [comment]
I'm no longer seeing that message, and I think the styling changes look great. However, since this PR makes the previews much larger, it makes [the bug that happens when you have too many workspaces](https://github.com/pop-os/gnome-shell-extension-vertical-overview/issues/5) a lot more obvious. I can approve this PR since it doesn't cause that bug, but I'm not sure how we feel about merging it until that bug is fixed.

**Comment by jackpot51** [comment]
@leviport I think we merge this and focus on that bug next. It would be good for everyone to have the styling updates

**Review by leviport — APPROVED** [review]

**Pull request merged**
