### PR TITLE
Fix cosmic workspaces for Jammy jellyfish

### LINKED ISSUE #52: Broken in Jammy
tracking issue. Already fixed by #51

### PR DESCRIPTION
**Pull request by 13r0ck**
- [x] use the correct protoype
Caused by gnome javascript PR: https://gitlab.gnome.org/GNOME/gjs/-/commit/e74701596c2ff9880cd39289b9649bb490951091#03566cbfedf849175708a56bfbbc92fe4cd7a28f
- [x] merge upstream changes
Caused by gnome-shell PR: https://gitlab.gnome.org/GNOME/gnome-shell/-/commit/5d1d4b56c6a804aec324ca8e97f7e045ce49e958

~~There are potentially more upstream changes, but that should be the bulk of it.~~

### CODE REVIEW

**Comment by ids1024** [comment]
Cosmic-workspaces is a fork of https://github.com/RensAlthuis/vertical-overview, so presumably they'd be interested in fixes here (if it doesn't break compatibility with older Gnome Shell releases; not sure if additional conditional logic would be needed).

**Comment by 13r0ck** [comment]
@ids1024 
Absolutely! I mentioned upstreaming to vertical overview in my meeting notes this morning :smile:. After I get it 100% working here I will upstream.

**Comment by 13r0ck** [comment]
Up-streamed https://github.com/RensAlthuis/vertical-overview/pull/101

**Review by jacobgkau — APPROVED** [review]
This gets cosmic-workspaces working on 22.04.

**Review by jackpot51 — APPROVED** [review]

**Pull request merged**
