### PR TITLE
Use (dis)connectObject()

### LINKED ISSUE #134: Opening apps with dock creates many system journal logs
Only if workspaces view has been opened since the start of gnome-shell

```
Apr 08 15:05:22 pop-os dbus-daemon[1879]: [session uid=1000 pid=1879] Activating service name='org.gnome.Nautilus' requested by ':1.368' (uid=1000 pid=95545 comm="/usr/bin/gnome-shell ")
Apr 08 15:05:22 pop-os gnome-shell[95545]: Object Clutter.Actor (0x5640cebe69a0), has been already disposed — impossible to get any property from it. This might be caused by the object having been destroyed from C code using something such as destroy(), dispose(), or remove() vfuncs.
Apr 08 15:05:22 pop-os gnome-shell[95545]: JS ERROR: TypeError: this._container.layout_manager is null
Apr 08 15:05:22 pop-os gnome-shell[95545]: == Stack trace for context 0x5640cb791190 ==
Apr 08 15:05:22 pop-os gnome-shell[95545]: #0   5640cbcfa4a0 i   resource:///org/gnome/shell/ui/workspace.js:1409 (dfc0a06b50 @ 242)
Apr 08 15:05:22 pop-os gnome-shell[95545]: #1   7ffd22efacd0 b   resource:///org/gnome/shell/ui/workspace.js:1274 (dfc0a06600 @ 465)
Apr 08 15:05:22 pop-os gnome-shell[95545]: #2   5640cbcfa418 i   resource:///org/gnome/shell/ui/workspace.js:1235 (dfc0a06650 @ 84)
Apr 08 15:05:22 pop-os gnome-shell[95545]: Object Clutter.Actor (0x5640d189d300), has been already disposed — impossible to get any property from it. This might be caused by the object having been destroyed from C code using something such as destroy(), dispose(), or remove() vfuncs.
Apr 08 15:05:22 pop-os gnome-shell[95545]: JS ERROR: TypeError: this._container.layout_manager is null
Apr 08 15:05:22 pop-os gnome-shell[95545]: == Stack trace for context 0x5640cb791190 ==
Apr 08 15:05:22 pop-os gnome-shell[95545]: #0   7ffd22efa660 b   resource:///org/gnome/shell/ui/workspace.js:1409 (dfc0a06b50 @ 242)
Apr 08 15:05:22 pop-os gnome-shell[95545]: #1   7ffd22efacd0 b   resource:///org/gnome/shell/ui/workspace.js:1274 (dfc0a06600 @ 465)
Apr 08 15:05:22 pop-os gnome-shell[95545]: #2   5640cbcfa418 i   resource:///org/gnome/shell/ui/workspace.js:1235 (dfc0a06650 @ 84)
Apr 08 15:05:22 pop-os gnome-shell[95545]: Object Clutter.Actor (0x5640d189df80), has been already disposed — impossible to get any property from it. This might be caused by the object having been destroyed from C code using something such as destroy(), dispose(), or remove() vfuncs.
Apr 08 15:05:22 pop-os gnome-shell[95545]: == Stack trace for context 0x5640cb791190 ==
Apr 08 15:05:22 pop-os gnome-shell[95545]: #0   7ffd22efac00 b   resource:///org/gnome/shell/ui/workspace.js:1409 (dfc0a06b50 @ 242)
Apr 08 15:05:22 pop-os gnome-shell[95545]: #1   7ffd22efacd0 b   resource:///org/gnome/shell/ui/workspace.js:1274 (dfc0a06600 @ 465)
Apr 08 15:05:22 pop-os gnome-shell[95545]: #2   5640cbcfa418 i   resource:///org/gnome/shell/ui/workspace.js:1235 (dfc0a06650 @ 84)
Apr 08 15:05:22 pop-os gnome-shell[95545]: JS ERROR: TypeError: this._container.layout_manager is null
Apr 08 15:05:22 pop-os gnome-shell[95545]: Object Clutter.Actor (0x5640d1a74c90), has been already disposed — impossible to get any property from it. This might be caused by the object having been destroyed from C code using something such as destroy(), dispose(), or remove() vfuncs.
Apr 08 15:05:22 pop-os gnome-shell[95545]: == Stack trace for context 0x5640cb791190 ==
Apr 08 15:05:22 pop-os gnome-shell[95545]: #0   7ffd22efac00 b   resource:///org/gnome/shell/ui/workspace.js:1409 (dfc0a06b50 @ 242)
Apr 08 15:05:22 pop-os gnome-shell[95545]: #1   7ffd22efacd0 b   resource:///org/gnome/shell/ui/workspace.js:1274 (dfc0a06600 @ 465)
Apr 08 15:05:22 pop-os gnome-shell[95545]: #2   5640cbcfa418 i   resource:///org/gnome/shell/ui/workspace.js:1235 (dfc0a06650 @ 84)
Apr 08 15:05:22 pop-os gnome-shell[95545]: JS ERROR: TypeError: this._container.layout_manager is null
Apr 08 15:05:22 pop-os gnome-shell[95545]: Object Clutter.Actor (0x5640cebe69a0), has been already disposed — impossible to get any property from it. This might be caused by the object having been destroyed from C code using something such as destroy(), dispose(), or remove() vfuncs.
Apr 08 15:05:22 pop-os gnome-shell[95545]: == Stack trace for context 0x5640cb791190 ==
Apr 08 15:05:22 pop-os gnome-shell[95545]: #0   7ffd22efac00 b   resource:///org/gnome/shell/ui/workspace.js:1409 (dfc0a06b50 @ 242)
Apr 08 15:05:22 pop-os gnome-shell[95545]: #1   7ffd22efacd0 b   resource:///org/gnome/shell/ui/workspace.js:1274 (dfc0a06600 @ 465)
Apr 08 15:05:22 pop-os gnome-shell[95545]: #2   5640cbcfa418 i   resource:///org/gnome/shell/ui/workspace.js:1235 (dfc0a06650 @ 84)
Apr 08 15:05:22 pop-os gnome-shell[95545]: JS ERROR: TypeError: this._container.layout_manager is null
Apr 08 15:05:22 pop-os gnome-shell[95545]: Object Clutter.Actor (0x5640d189d300), has been already disposed — impossible to get any property from it. This might be caused by the object having been destroyed from C code using something such as destroy(), dispose(), or remove() vfuncs.
Apr 08 15:05:22 pop-os gnome-shell[95545]: JS ERROR: TypeError: this._container.layout_manager is null
Apr 08 15:05:22 pop-os gnome-shell[95545]: == Stack trace for context 0x5640cb791190 ==
Apr 08 15:05:22 pop-os gnome-shell[95545]: #0   7ffd22efac00 b   resource:///org/gnome/shell/ui/workspace.js:1409 (dfc0a06b50 @ 242)
Apr 08 15:05:22 pop-os gnome-shell[95545]: #1   7ffd22efacd0 b   resource:///org/gnome/shell/ui/workspace.js:1274 (dfc0a06600 @ 465)
Apr 08 15:05:22 pop-os gnome-shell[95545]: #2   5640cbcfa418 i   resource:///org/gnome/shell/ui/workspace.js:1235 (dfc0a06650 @ 84)
Apr 08 15:05:22 pop-os gnome-shell[95545]: Object Clutter.Actor (0x5640d189df80), has been already disposed — impossible to get any property from it. This might be caused by the object having been destroyed from C code using something such as destroy(), dispose(), or remove() vfuncs.
Apr 08 15:05:22 pop-os gnome-shell[95545]: JS ERROR: TypeError: this._container.layout_manager is null
Apr 08 15:05:22 pop-os gnome-shell[95545]: == Stack trace for context 0x5640cb791190 ==
Apr 08 15:05:22 pop-os gnome-shell[95545]: #0   7ffd22efaaa0 b   resource:///org/gnome/shell/ui/workspace.js:1409 (dfc0a06b50 @ 242)
Apr 08 15:05:22 pop-os gnome-shell[95545]: #1   7ffd22efab70 b   resource:///org/gnome/shell/ui/workspace.js:1274 (dfc0a06600 @ 465)
Apr 08 15:05:22 pop-os gnome-shell[95545]: #2   7ffd22efb290 b   resource:///org/gnome/shell/ui/workspace.js:1235 (dfc0a06650 @ 84)
Apr 08 15:05:22 pop-os gnome-shell[95545]: Object Clutter.Actor (0x5640d1a74c90), has been already disposed — impossible to get any property from it. This might be caused by the object having been destroyed from C code using something such as destroy(), dispose(), or remove() vfuncs.
Apr 08 15:05:22 pop-os gnome-shell[95545]: JS ERROR: TypeError: this._container.layout_manager is null
Apr 08 15:05:22 pop-os gnome-shell[95545]: == Stack trace for context 0x5640cb791190 ==
Apr 08 15:05:22 pop-os gnome-shell[95545]: #0   7ffd22efb100 b   resource:///org/gnome/shell/ui/workspace.js:1409 (dfc0a06b50 @ 242)
Apr 08 15:05:22 pop-os gnome-shell[95545]: #1   7ffd22efb1d0 b   resource:///org/gnome/shell/ui/workspace.js:1274 (dfc0a06600 @ 465)
Apr 08 15:05:22 pop-os gnome-shell[95545]: #2   7ffd22efb290 b   resource:///org/gnome/shell/ui/workspace.js:1235 (dfc0a06650 @ 84)

```

### PR DESCRIPTION
**Pull request by 13r0ck**
Updating the Init function to match changes from
GNOME/gnome-shell commit 26235bbe5433c48b81bd3917aaf9ef14ff1929b2

https://github.com/pop-os/gnome-shell/commit/26235bbe5433c48b81bd3917aaf9ef14ff1929b2

Closes pop-os/cosmic-dock#134

### CODE REVIEW

**Comment by 13r0ck** [comment]
I am certain there are other situations where our extensions have many warning logs, but this is the last one I have found. @pop-os/quality-assurance If you know of any others please put the issue in the 22.04 project list, and link them here for me. Thanks!

**Review by mmstick — APPROVED** [review]

**Comment by jacobgkau** [comment]
On 452ebcd, I'm still seeing multiple `Object St.Bin (...), has been already disposed - impossible to access it.` logs when I open the Workspaces menu and then launch an app from the dock. Should this entirely fix https://github.com/pop-os/cosmic-dock/issues/134 or just improve it?

**Comment by 13r0ck** [comment]
@jacobgkau 
The linked issue is for messages like
```
Apr 08 15:05:22 pop-os gnome-shell[95545]: == Stack trace for context 0x5640cb791190 ==
Apr 08 15:05:22 pop-os gnome-shell[95545]: #0   7ffd22efac00 b   resource:///org/gnome/shell/ui/workspace.js:1409 (dfc0a06b50 @ 242)
Apr 08 15:05:22 pop-os gnome-shell[95545]: #1   7ffd22efacd0 b   resource:///org/gnome/shell/ui/workspace.js:1274 (dfc0a06600 @ 465)
Apr 08 15:05:22 pop-os gnome-shell[95545]: #2   5640cbcfa418 i   resource:///org/gnome/shell/ui/workspace.js:1235 (dfc0a06650 @ 84)
Apr 08 15:05:22 pop-os gnome-shell[95545]: JS ERROR: TypeError: this._container.layout_manager is null
```
so that is all that I was looking at.

There might be another issue? But I don't see the `Object St.Bin (...), has been already disposed - impossible to access it.` messages on my machine. It might be because I have all of my recent PRs installed on my machine? If you are on master staging do you still see those messages?

**Review by jacobgkau — APPROVED** [review]
> If you are on master staging do you still see those messages?

Yes, I already had master staging added on the machine. Just now, I got the messages I was referring to showing up again on one attempt, but am now seeing them not show up on several subsequent GNOME Shell restarts (even after uninstalling this branch.) Not sure what was causing them.

Your issue https://github.com/pop-os/cosmic-dock/issues/134 included some "has already been disposed" messages, which is why I thought they were related:

> `Apr 08 15:05:22 pop-os gnome-shell[95545]: Object Clutter.Actor (0x5640cebe69a0), has been already disposed — impossible to get any property from it. This might be caused by the object having been destroyed from C code using something such as destroy(), dispose(), or remove() vfuncs.`

I see that the line you quoted is for `Object Clutter.Actor` and the one I quoted is for `Object St.Bin`. I can confirm this PR removes the log lines referred to in https://github.com/pop-os/cosmic-dock/issues/134, so I'll go ahead and approve.

**Comment by 13r0ck** [comment]
@jacobgkau sounds good. Thanks! Sorry for the confusion. If you could create an issue with the other log messages you were seeing that would be awesome.

**Pull request merged**
