### PR TITLE
Improve functionality with custom docks

### LINKED ISSUE #35: Workspaces overview disappears after suspend until extension / shell restarted
**Distribution (run `cat /etc/os-release`):**
 Pop 21.10
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**
Gnome 40.4.0 X11 (have not tried Wayland)
Cosmic version 1
Cosmic workspaces version 6
Pop shell version 2

**Issue/Bug Description:**
After a suspend and subsequently resume the workspace menu disappears. You can still gesture left and get the application overview but there are no thumbnails of all your workspaces on the left-hand side anymore. Can be fixed with ALT+F2 + "r", disabling and reenabling the workspaces extension or restarting the computer until the next suspend. Screenshots below.

**Steps to reproduce (if you know):**
Suspend and resume PC.

**Expected behavior:**
Workspaces view persists.

**Other Notes:**
I am using Dash to Dock, Cosmic Dock is disabled. Happens with Nvidia and Intel graphics.

_Normal view_
image
_After suspend_
image

Unrelated, but with a lot of workspaces the thumbnails shrink towards the right when they could shrink towards the left and leave more space for your windows overview.

### PR DESCRIPTION
**Pull request by 13r0ck**
Keeps workspaces view working even if cosmic-dock is disabled.

Might fix #35

# Before
Screenshot from 2022-01-31 19-26-42

# After 
Screenshot from 2022-01-31 19-24-36

### CODE REVIEW

**Comment by 13r0ck** [comment]
Should this add a dconf value to shrink the workspace picker by a custom amount? That way if someone is using a custom dock they can manually set a value to prevent them from overlapping?

**Review by jackpot51 — DISMISSED** [review]

**Comment by XV-02** [comment]
I didn't see any suggestion of regression with this fix.

**Comment by 13r0ck** [comment]
I am converting this to a draft temporarily as I nail down the custom offset implementation

**Comment by 13r0ck** [comment]
This does a few things:

1. Keeps the workspaces view responsive with cosmic-dock disabled
2. Improves UX while using custom docks
    a. Add dconf values for moving the workspace picker left/right
    b. Add dconf value for extending/shrinking the bottom of the workspace picker
    
2(a & b) allow for the user to specify the percentage of the screen that their custom dock will take. This isn't as integrated with the dock like cosmic-dock is, there is no animation in/out the value is constant. 

Note: After installing a new dock like dash-to-dock or floating-dock, the workspaces picker will still shrink to a dot. Though, after a reboot (or gnome-shell restart) the dot issue will be fixed. There seems to be a conflict with the "rug getting pulled out from under" cosmic workspaces. Which is then causing the workspace picker `Actor` to be assigned a negative height, which then fails an assertion in mutter that is called by gnome-shell. The effort required to fix this unfortunately out weighs the issue, when just rebooting after changing settings in the dock solves the issue for all following reboots.

**Review by jackpot51 — APPROVED** [review]

**Comment by jacobgkau** [comment]
This expands the workspace picker vertically when the COSMIC Dock extension is disabled, as shown in the PR description's screenshots. However, the workspace picker doesn't shrink when the GNOME favorites bar grows:

Screenshot from 2022-03-08 12-07-02

It seems like the reason the workspace picker's height was limited before was to avoid that overlap. Does it make sense for the picker to not dodge the favorites bar at all?

**Comment by 13r0ck** [comment]
@jacobgkau 
> It seems like the reason the workspace picker's height was limited before was to avoid that overlap. Does it make sense for the picker to not dodge the favorites bar at all?

from comment above:
```
improves UX while using custom docks
a. Add dconf values for moving the workspace picker left/right
b. Add dconf value for extending/shrinking the bottom of the workspace picker
```

The issue you are seeing is because cosmic-workspaces doesn't know how tall the dash is. The picker is shorter with default settings, because it reads the height of cosmic-dock, and shortens itself by that amount. There is probably some way to read the dash's height, but I didn't look into it because then we would have to read the height values of every possible custom dock that someone might install. So I settled for the dconf values. Meaning that if a user disables cosmic-dock, then they will have to manually set the value to shrink and/or move the workspace picker by.

Though this PR isn't really important to QA. A user reported that with a custom dock installed, the workspaces view still doesn't work after suspend. I am not sure when I will have time to look at this again. Maybe if/when we port our extensions to gnome 42, I'm not sure

**Comment by 13r0ck** [comment]
This will be closed to prioritize jammy. Tracking issue is #61

**Pull request closed without merging**
