### PR TITLE
Fix screen lock during full-screen video/app

### LINKED ISSUE #33: GNOME Shell crash when locking while full-screen apps are open
**Steps to recreate:**
1. Open a full-screen YouTube video.
2. Repeatedly lock and unlock the display.

**Observed behavior:** GNOME Shell crashes occur; on some systems (lemp10), GNOME Shell just restarts, but on other systems (reported via users on Mattermost), this causes an "Oh no! Something has gone wrong..." screen.

**Expected behavior:** No crash.

**Other notes:** The issue goes away after disabling the Cosmic Workspaces extension via the Extensions app, which is why I'm opening the issue in this repo.

### PR DESCRIPTION
**Pull request by jacobgkau**
Pulls in unmerged upstream PR https://github.com/RensAlthuis/vertical-overview/pull/79 to fix a GNOME Shell crash when locking the display while a full-screen video or app is open.

Fixes https://github.com/pop-os/cosmic-workspaces/issues/33.

### CODE REVIEW

**Comment by jacobgkau** [comment]
It looks like we may have lost our panel color in the current version of this; that will need to be added back.

**Comment by 13r0ck** [comment]
Can you please add a screenshot? I'm not seeing the color change?

**Comment by jacobgkau** [comment]
> Can you please add a screenshot? I'm not seeing the color change?

It's very subtle, but if you use a color picker app (I use KColorChooser), you'll see it was `#211F1F` before and is pure black now; here's a comparison:

Screenshot from 2021-12-30 16-45-50
Screenshot from 2021-12-30 16-45-26

**Review by jackpot51 — APPROVED** [review]

**Comment by 13r0ck** [comment]
I can confirm that that regression is fixed by pop-os/gtk-theme#567.
I will finish testing this tomorrow for approval (It should be fine), but pop-os/gtk-theme#567 will need to be merged first.

**Review by 13r0ck — APPROVED** [review]
:+1: 

This works. 25+ screen locks later with full screen video. No crash.

__THIS REQUIRES pop-os/gtk-theme#567__

Please merge both at the same time. Thanks

**Pull request merged**
