### PR TITLE
Background not updating after reboot.

### PR DESCRIPTION
**Pull request by Cereal-Killa**
Steps to reproduce:
1) Assign a custom background.
2) Restart.
3) Assign a "default" background.
4) Launch workspaces.
5) The previously assigned custom background displays instead of the "default" background that was just assigned.

### CODE REVIEW

**Review by jacobgkau — CHANGES_REQUESTED** [review]
This fixes the wallpaper switching behavior, but it introduces a dark vignette in the Workspaces menu:

Screenshot from 2022-02-17 10-21-50

Fixing this may be as simple as setting `vignette: false,` on line 31.

**Comment by Cereal-Killa** [comment]
True, I wasn't sure if the vignette would be nice to have or not, removing it.

> This fixes the wallpaper switching behavior, but it introduces a dark vignette in the Workspaces menu:

You're right, wasn't there before, removed it.

**Review by jacobgkau — CHANGES_REQUESTED** [review]
Vignette has been removed, and this still fixes the wallpaper switching bug.

This introduces regressions in the Workspaces menu after changing display configuration; after plugging in a display, the wallpaper is stretched and does not completely fill the external display:

https://user-images.githubusercontent.com/7199422/154539544-edd278aa-e542-413c-b976-3fe1428cb83f.mp4

After unplugging a display, the internal display's wallpaper doesn't show:

https://user-images.githubusercontent.com/7199422/154539703-1775578a-4f30-4e1a-9aeb-4718b3bd2c3b.mp4

These issues are both fixed by restarting GNOME Shell.

**Comment by Cereal-Killa** [comment]
> This introduces regressions in the Workspaces menu after changing display configuration; after plugging in a display, the wallpaper is stretched and does not completely fill the external display:

Thank you for the regression samples, will work on this.

**Comment by Cereal-Killa** [comment]
@jacobgkau This commit contains the bare minimum changes that in my tests fixes the background glitch upon reboot, apparently "destroy" should be only triggered when reset() is called and not every time updateStaticBackgrounds() executes. Did some basic multi-monitor testing here and it seemed ok after removing and inserting them again, let me know if it works for you as well.

**Review by jacobgkau — CHANGES_REQUESTED** [review]
There's been a change in specifics, but there are still regressions. After plugging in a display, I still see the internal display's wallpaper zoom in and cover up part of the external display's wallpaper:

Screenshot from 2022-02-17 13-26-24

Likewise, after unplugging a display, the wallpaper still doesn't display properly:

Screenshot from 2022-02-17 13-27-22

I cannot recreate these issues on master (fb53648).

**Comment by Cereal-Killa** [comment]
> After plugging in a display, I still see the internal display's wallpaper zoom in and cover up part of the external display's wallpaper:

Question, could you explain exactly how to reproduce this so I can test it correctly? At the moment I'm unplugging the monitor cable which renders a black screen and then displays the background correctly without stretching out to the other monitor; then I plug it back it and the screen blinks again and finally displays the desktop with the background correctly again so I'm clearly not doing the same thing as you are then will need some help so I can do the proper testing on my end in order to work on the issue; I have 4 monitors including one at the top of the other so this should help covering all possibilities, but I did test with just 2 and still no luck reproducing this. I tried to do a screen recording but unplugging the monitor renders an error in the recorder app:

[X11Input::InputThread] Error: Can't get image (using shared memory)!
    Usually this means the recording area is not completely inside the screen. Or did you change the screen resolution?
[X11Input::InputThread] Exception 'X11Exception' in input thread.

**Comment by jacobgkau** [comment]
> Question, could you explain exactly how to reproduce this so I can test it correctly?

1. Boot (or restart GNOME Shell) without an external display connected.
2. Plug in an external display.
3. Open Workspaces.

Alternatively:

1. Boot (or restart GNOME Shell) with an external display connected.
2. Open and close Workspaces.
2. Unplug the external display.
3. Open Workspaces.

For the second case, opening Workspaces at least once before unplugging the display seems to be necessary to trigger the issue.

I am testing on an Oryx Pro, and the issues occur in both NVIDIA mode and Hybrid mode (where Hybrid has the display server driven by an Intel GPU.)

**Comment by Cereal-Killa** [comment]
@jacobgkau Thank you. I gave it a try here and I've noticed that on upstream (vertical-overview) it exhibits the same issue when setup to look like cosmic-workspaces, by turning on static-background and scaling-workspaces. I'll be looking into it.

**Comment by Cereal-Killa** [comment]
@jacobgkau I came up with the fix, will create a pull request on upstream as well.

https://github.com/RensAlthuis/vertical-overview/pull/99

**Review by jackpot51 — APPROVED** [review]

**Review by jacobgkau — APPROVED** [review]
The wallpaper bug is still fixed. The multi-monitor regression is no longer present. All Workspaces options exposed in desktop-widget are still functioning as expected.

**Pull request merged**
