### PR TITLE
fix: multiple displays with different resolutions + make indicators vertical

### LINKED ISSUE #55: 22.04: workspace OSD is horizontal / default Gnome
The styling of the workspace indicator OSD when changing workspaces is default Gnome and horizontal:

Screenshot from 2022-03-29 11-04-15
Screenshot from 2022-03-29 11-04-16

It also collides with the dock with default dock settings.

### PR DESCRIPTION
**Pull request by 13r0ck**
- [x] Fix workspace picker scaling on multiple displays with different resolutions
- [x] Fix workspace indicators when using hotkeys to be vertical
dots
 
 Requires pop-os/cosmic-dock#132

### CODE REVIEW

**Review by jackpot51 — DISMISSED** [review]

**Comment by 13r0ck** [comment]
Sorry I had a print statement that I needed to delete. Then I force pushed the wrong thing :facepalm:

**Review by jackpot51 — DISMISSED** [review]

**Comment by 13r0ck** [comment]
[98ea4ac](https://github.com/pop-os/cosmic-workspaces/pull/56/commits/98ea4ac17eebc9c976ce954df3984009e18ab8dc) caused a regression. The workspaces box now overlaps the workspace picker again. I will need to fix that before this is approved.

**Comment by 13r0ck** [comment]
~~This is now ready for QA~~

**Comment by 13r0ck** [comment]
The most recent beta iso in jammy broke this again...

**Review by jackpot51 — DISMISSED** [review]

**Comment by jacobgkau** [comment]
Was this supposed to increase the size of the workspace picker?

Before:
Screenshot from 2022-03-30 16-38-07

After:
Screenshot from 2022-03-30 16-38-36

**Comment by 13r0ck** [comment]
@jacobgkau This also fixed a bug on some monitors where the picker would animate awkwardly when opening a third workspace. The fix results in a slightly larger picker on some screens

**Comment by 13r0ck** [comment]
Also, changing the dock location will break workspaces. As far as I am aware It isn't caused by this PR, rather something in cosmic-dock. Issue here: https://github.com/pop-os/cosmic-dock/issues/129

**Review by jacobgkau — CHANGES_REQUESTED** [review]
After the change, the workspace picker fits 5 workspaces, then starts shrinking. Referring to the [original COSMIC mockups](https://www.figma.com/file/F3QQlV7BYsj0Zwq9WhWnqg/Pop!_OS-COSMIC-21.04?node-id=260%3A829), that looks like about the number that would have fit, although those mockups include workspace name labels (and horizontal options), which also leads me to believe that we're not too concerned about the exact presentation of the workspace picker.

This fixes https://github.com/pop-os/cosmic-workspaces/issues/55.

This improves the HiDPI overlap situation described in https://github.com/pop-os/cosmic-workspaces/pull/54#pullrequestreview-923708512, although windows are now partially pushed off the edge of the screen on HiDPI (instead of overlapping the picker):

Screenshot from 2022-03-31 14-42-43

This also causes a HiDPI regression. On addw2 with the HiDPI daemon set to HiDPI mode (while connected to a 1440p external display), the picker is now oversized on the external display and undersized on the internal display, and windows on the internal display are not shown in the Workspaces menu:

Screenshot from 2022-03-31 14-44-39

**Comment by 13r0ck** [comment]
@jacobgkau this will not work until cosmic dock is fixed. https://github.com/pop-os/cosmic-workspaces/pull/56#issuecomment-1083744604

**Comment by jacobgkau** [comment]
> @jacobgkau this will not work until cosmic dock is fixed. [#56 (comment)](https://github.com/pop-os/cosmic-workspaces/pull/56#issuecomment-1083744604)

That issue is describing things breaking after dock state changes; this was happening on a fresh GNOME Shell restart (confirmed it's still happening on a fresh boot/login) and not after any state changes. If the issue needs to be renamed and/or you just want to get that fixed first, that's fine.

Edit: if I disable the Cosmic Dock extension and then restart GNOME Shell, the picker on the internal display does work (perhaps the HiDPI daemon is causing a state change), but the picker on the external display's scaling is still off/oversized (so it's not all that issue.)

**Comment by jacobgkau** [comment]
On [542f31b](https://github.com/pop-os/cosmic-workspaces/pull/56/commits/542f31b71d0cef7795115c5e0ee20c08afecec80) (along with the latest updates to other packages from over the weekend), I'm seeing windows disappear and not come back (with no workspace picker or indicators either) after entering the Workspaces menu. I have to restart GNOME Shell to recover. journalctl output:

```
Apr 04 09:34:10 pop-os gnome-shell[9628]: JS ERROR: TypeError: Main.overview.fadeOutDesktop is not a function
                                          animateToOverview@/usr/share/gnome-shell/extensions/cosmic-workspaces@system76.com/overviewControls.js:321:27
                                          animateToOverview@resource:///org/gnome/shell/ui/overview.js:82:24
                                          _animateVisible@resource:///org/gnome/shell/ui/overview.js:505:24
                                          show@resource:///org/gnome/shell/ui/overview.js:490:14
                                          gnome_40_enable/<@/usr/share/gnome-shell/extensions/pop-cosmic@system76.com/extension.js:237:23
                                          toggle@resource:///org/gnome/shell/ui/overview.js:596:18
```

**Comment by 13r0ck** [comment]
I will ping you when this is ready for QA

**Review by jackpot51 — DISMISSED** [review]

**Comment by jacobgkau** [comment]
I found one situation where windows are overlapping the workspace picker. This is 1080p internal + 1440p external, both LoDPI/100% scaled, and the external display has a window overlapping in the workspaces menu:

Screenshot from 2022-04-05 09-42-32

Happens whether or not the dock is enabled on the secondary display, and regardless of which side the workspace picker is on. It gets a little worse if the dock is set to the same side as the workspace picker (because the workspace picker shifts on the secondary display, even when the dock's not enabled on the secondary display):

Screenshot from 2022-04-05 09-46-24

It looks like when the dock _is_ enabled on the secondary display, the workspace picker shifts out of the way twice as much as it needs to on that display (but the window also shifts away slightly to match):

Screenshot from 2022-04-05 09-48-33

**Comment by 13r0ck** [comment]
Thanks!
I'm going to fix [8ecce20](https://github.com/pop-os/cosmic-workspaces/pull/56/commits/8ecce2091e623eb0fad4287168698325e0e00169) then I will fix that too.

**Comment by 13r0ck** [comment]
@jacobgkau how does that look now?

**Comment by jacobgkau** [comment]
If I set the dock and workspace picker to the same side of the screen and set the dock to always hide or intelligently hide, the dock shows in the Workspaces menu; interestingly, the workspace picker dodges the dock on the primary display, but not on the secondary display.

Screenshot from 2022-04-05 14-21-00

Aside from that, I am still seeing the extra space on the secondary display when the dock is enabled, although I would consider this one even more minor:

Screenshot from 2022-04-05 14-23-44

Looks like when the dock is set to always show, the picker dodges the dock on the second display whether the dock is enabled for the second display or not:

Screenshot from 2022-04-05 14-25-47

So not sure why it's trying to dodge further since it was already dodging (or whether that's part of the problem or not.)

On the bright side, I'm not seeing any instances of windows overlapping the workspace picker now, at least on LoDPI.

**Comment by 13r0ck** [comment]
The last commit should fix the overlapping workspace picker and dock.

The picker dodging the dock when the dock only shows on the primary monitor will still require one more commit. I need to figure how to get that dock configuration information into cosmic-workspaces

**Comment by 13r0ck** [comment]
@jacobgkau does [b80291b](https://github.com/pop-os/cosmic-workspaces/pull/56/commits/b80291b131585621dfe2c8fe6b3576155ff262f0) work?

**Review by jackpot51 — DISMISSED** [review]

**Comment by jackpot51** [comment]
https://github.com/pop-os/cosmic-dock/pull/132 will be in master staging soon, so you will need both that and workspaces-more-jammy-fixes for testing.

**Comment by jacobgkau** [comment]
[b80291b](https://github.com/pop-os/cosmic-workspaces/pull/56/commits/b80291b131585621dfe2c8fe6b3576155ff262f0) is working almost flawlessly. There are no more picker/dock/window overlaps. When the dock is set to always or intelligently hide, the workspace picker dodges it as expected:

Screenshot from 2022-04-06 09-13-00

When the dock is set to always show, we still get an extra dock's worth of space between the picker and the dock on the secondary display:

Screenshot from 2022-04-06 09-13-51

Is the cause for that apparent?

**Comment by 13r0ck** [comment]
Not sure ill look into it

**Comment by 13r0ck** [comment]
:crossed_fingers: [c304b50](https://github.com/pop-os/cosmic-workspaces/pull/56/commits/c304b50e26a2395467ef9331c471391f7cea8d37)

I found a few more cases where layout was a bit off, and I fixed those too. I tested on tripple monitors and I made a little table for testing
Screenshot from 2022-04-06 11-58-04

**Comment by jacobgkau** [comment]
I am now seeing the dock overlap the workspace picker on the secondary screen when the dock's set to always or intelligently hide again:

Screenshot from 2022-04-06 13-49-32

**Comment by 13r0ck** [comment]
too many settings lol. Try now

**Comment by jacobgkau** [comment]
Pickiest one yet, secondary display workspace indicator doesn't dodge a bottom-positioned dock set to auto or intelligently hide. (It does dodge this position when the dock is set to always show.)

Screenshot from 2022-04-06 15-27-07

**Comment by 13r0ck** [comment]
Good catch. That should be resolved now.

**Comment by jacobgkau** [comment]
A few things noticed going through all possible combinations again:

On a HiDPI system w/ LoDPI external display:

- When the dock and workspace picker are both set to the left side, and the dock is set to show on the primary display only, the secondary display dodges when it doesn't need to. (This doesn't happen with dock/picker on the right side, and I also didn't see it happen on a LoDPI system.)

Screenshot from 2022-04-06 17-42-17

- When the dock is set to show on both displays, the external display's workspace picker dodges the width of two docks (again, only on HiDPI.)

Screenshot from 2022-04-06 17-47-44

- On both a HiDPI and LoDPI internal display w/ LoDPI external, whenever the dock is set to auto or intelligently hide, it disappears from Workspaces if the cursor goes over it and then away again, which is [not necessarily desirable](https://github.com/pop-os/cosmic-workspaces/issues/46) but not a regression. However, once the workspace picker on the internal display adjusts to fill in the space left by the dock, the external display's picker also resizes (on the HiDPI system it seems like I need to mouse over it for that to happen), even though its dock hasn't hidden. This does _not_ happen when the dock is on a side, only the bottom.

Screenshot from 2022-04-06 17-51-45

Just to be clear, we're at the point now where this is not going to hold up release, but any further polish possible is welcome.

**Comment by 13r0ck** [comment]
[84763b8](https://github.com/pop-os/cosmic-workspaces/pull/56/commits/84763b85a7336028581c42f65e619a14657e9e52) should fix the 2x dock width dodging with HiDPI primary & LoDPI secondary. 


>  ... if the cursor goes over it and then away again ...

This happens because the picker's height is dictated by the `mainDock` height, so all picker heights are listening to the primary display's dock to calculate their height. It is possible to query each dock for each display and that would fix the issue, I can do that if you really want.
I do think it is better UX for the dock to stay open the full time the workspaces view is open (the issue you linked above), and making a PR in cosmic-dock to do that would fix this issue here, if that is done then querying each dock would become unnecessary CPU cycles, as getting the dock for each display requires iterating through the list of all docks. Meaning we would have to make another PR back here to remove the work.

personally I would rather kill two birds with one stone with a cosmic-dock PR, what do you think?

**Comment by jacobgkau** [comment]
> personally I would rather kill two birds with one stone with a cosmic-dock PR, what do you think?

This makes perfect sense to me, no point making the dodging behavior more complicated than it needs to be if it's easier to just take care of that other quirk.

All other behavior's looking good on HiDPI, just going to double-check again on LoDPI before approving this one.

**Review by jacobgkau — APPROVED** [review]
Aside from responding to the dock hiding when the Workspaces menu is already showing, the workspace picker is appropriately and independently dodging the dock and giving adequate room to the windows in all combinations of primary/secondary display dock and workspace picker placement. (This PR also still includes the vertical workspace indicators, which are still working.)

**Review by jackpot51 — APPROVED** [review]

**Pull request merged**
