### PR TITLE
Cherry-pick upstream clean up commits

### PR DESCRIPTION
**Pull request by carlwgeorge**
After this repo forked from upstream, some clean up was done to drop custom code in favor of build in functions.  These commits seem appropriate for cosmic-workspaces.

### CODE REVIEW

**Review by Conan-Kudo — APPROVED** [review]

**Review by jackpot51 — APPROVED** [review]

**Review by jacobgkau — CHANGES_REQUESTED** [review]
With this change, the extension is failing to start. I get this in journalctl:
```
Nov 01 13:17:53 pop-os gnome-shell[2497]: [VERTICAL-OVERVIEW] starting overrides
Nov 01 13:17:53 pop-os gnome-shell[2497]: JS ERROR: Extension cosmic-workspaces@system76.com: ReferenceError: getSettings is not defined
                                          bindSetting@/usr/share/gnome-shell/extensions/cosmic-workspaces@system76.com/util.js:45:13
                                          bindSettings@/usr/share/gnome-shell/extensions/cosmic-workspaces@system76.com/extension.js:81:10
                                          enable@/usr/share/gnome-shell/extensions/cosmic-workspaces@system76.com/extension.js:24:5
                                          _callExtensionEnable@resource:///org/gnome/shell/ui/extensionSystem.js:168:32
                                          loadExtension@resource:///org/gnome/shell/ui/extensionSystem.js:351:26
                                          _loadExtensions/<@resource:///org/gnome/shell/ui/extensionSystem.js:597:18
                                          collectFromDatadirs@resource:///org/gnome/shell/misc/fileUtils.js:27:28
                                          _loadExtensions@resource:///org/gnome/shell/ui/extensionSystem.js:572:19
                                          _enableAllExtensions@resource:///org/gnome/shell/ui/extensionSystem.js:606:18
                                          _sessionUpdated@resource:///org/gnome/shell/ui/extensionSystem.js:637:18
                                          init@resource:///org/gnome/shell/ui/extensionSystem.js:57:14
                                          _initializeUI@resource:///org/gnome/shell/ui/main.js:278:22
                                          start@resource:///org/gnome/shell/ui/main.js:175:5
                                          @<main>:1:47
```
It looks like a line is still calling the `getSettings` function that is being removed: https://github.com/pop-os/cosmic-workspaces/blob/9c6654509732ae6150399b058b868ed91f906412/util.js#L45

**Comment by carlwgeorge** [comment]
2f04585f5e6dbc56dab6fac5c5c5a72568e4e6fc in this PR updates that line from `getSettings` to `ExtensionUtils.getSettings`.  The merge commit (9c6654509732ae6150399b058b868ed91f906412) is undoing that change.

**Comment by jacobgkau** [comment]
I see. This PR was submitted in succession with https://github.com/pop-os/cosmic-workspaces/pull/14 and had conflicts after that one was merged. I'll try to fix the merge commit.

**Review by jacobgkau — APPROVED** [review]
Basic functionality, multi-monitor/vertical workspaces display, and preferences window (including preference adjustment) are all working. All Workspaces settings in desktop-widget are also working, including the screen edge for the workspace picker. Seeing some problems with window preview placement, but those are present in the current stable version: https://github.com/pop-os/cosmic-workspaces/issues/4

**Pull request merged**
